import Button from "../ui/Button.jsx";
import { departmentLabel } from "../../utils/planningLabels.js";

function timeLabel(timestamp) {
  return timestamp?.split("T")[1]?.slice(0, 5) ?? "";
}

function proofLabel(proofState) {
  if (proofState === "FULLY_OPTIMAL") return "Optimal plan proven";
  if (proofState === "FEASIBLE_BOUNDED") return "Valid bounded plan";
  return proofState ? proofState.replaceAll("_", " ").toLowerCase() : "Plan generated";
}

export default function OptimizerControls({
  optimizationStatus,
  optimizationError,
  plan,
  horizon,
  onOptimize,
  canOptimize,
  tasks,
}) {
  const taskById = new Map(tasks.map((task) => [task.task_id, task]));
  const busy = optimizationStatus === "loading";
  const statusText = busy
    ? "Optimizing plan..."
    : optimizationStatus === "success"
      ? proofLabel(plan?.proof_state)
      : optimizationStatus === "error"
        ? "Optimization failed"
        : "Ready";
  const validSavings =
    plan?.comparison?.same_task_set &&
    plan.comparison.closure_saved_minutes != null &&
    plan.comparison.closure_reduction_percent != null;

  return (
    <section className="optimizer-controls" aria-labelledby="optimizer-heading">
      <div className="workspace-column-heading">
        <div>
          <span className="planner-kicker">Plan action</span>
          <h2 id="optimizer-heading">Optimizer Controls</h2>
        </div>
      </div>

      <label className="planner-field">
        <span>Planning Horizon</span>
        <select value="fixture" disabled>
          <option value="fixture">
            {horizon ? `${timeLabel(horizon.start_time)}–${timeLabel(horizon.end_time)} · Fixture` : "Loading..."}
          </option>
        </select>
      </label>

      <label className="planner-field">
        <span>Planning Profile</span>
        <select value="availability" disabled>
          <option value="availability">Availability First</option>
        </select>
      </label>

      <Button
        className="planner-optimize-button"
        onClick={onOptimize}
        disabled={!canOptimize}
        ariaBusy={busy}
      >
        {busy ? "Restart Optimization" : "Optimize Plan"}
      </Button>

      <div
        className={`optimizer-status status-${optimizationStatus}`}
        role="status"
        aria-live="polite"
      >
        <span className="optimizer-status-dot" aria-hidden="true" />
        <div>
          <small>Status</small>
          <strong>{statusText}</strong>
        </div>
      </div>

      {optimizationError ? (
        <div className="optimizer-error" role="alert">
          <strong>{optimizationError.code ?? "REQUEST_FAILED"}</strong>
          <span>{optimizationError.message}</span>
        </div>
      ) : null}

      {plan ? (
        <div className="optimizer-result-summary">
          <dl>
            <div><dt>Possessions</dt><dd>{plan.blocks.length}</dd></div>
            <div><dt>Integrated</dt><dd>{plan.metrics.integrated_blocks}</dd></div>
            <div><dt>Scheduled tasks</dt><dd>{new Set(plan.blocks.flatMap((block) => block.tasks)).size}</dd></div>
          </dl>
          <p>
            <strong>Non-integrated CP-SAT comparison</strong>
            {validSavings
              ? `${plan.comparison.closure_saved_minutes} min (${plan.comparison.closure_reduction_percent.toFixed(1)}%) less possession time.`
              : "No same-work savings claim is available."}
          </p>
          <div className="optimizer-unscheduled">
            <strong>Unscheduled maintenance</strong>
            {plan.unscheduled_tasks.length > 0 ? (
              <ul>{plan.unscheduled_tasks.map((id) => (
                <li key={id}>
                  <strong>{taskById.get(id)?.task_type ?? "Maintenance task"}</strong>
                  <span>{departmentLabel(taskById.get(id)?.department)} · {id}</span>
                </li>
              ))}</ul>
            ) : (
              <span>None</span>
            )}
          </div>
        </div>
      ) : null}

      <p className="optimizer-local-note">
        Results are generated by FastAPI from the synthetic fixture and the RailSync CP-SAT engine.
      </p>
    </section>
  );
}
